version: "3"

services:
  postgres:
    env_file:
      - ../.env
    container_name: dev-pmanage-postgres
    image: postgres:11.6-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    container_name: dev-pmanage-redis
    image: redis:alpine
    ports:
      - "6379:6379"
  mongo:
    container_name: dev-pmanage-mongo
    image: mongo
    ports:
      - "27017:27017"
  mailhog:
    container_name: dev-pmanage-mailhog
    image: mailhog/mailhog
    ports:
      - "8025:8025"
      - "1025:1025"

volumes:
  postgres_data:
